# Generated by Django 3.2.1 on 2022-03-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_customuser_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sms_code',
            field=models.IntegerField(null=True),
        ),
    ]
