# Generated by Django 3.2.1 on 2022-04-02 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0005_auto_20220402_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='car_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='car_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_driver',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='klass',
        ),
    ]
