# Generated by Django 3.2.1 on 2022-04-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0006_auto_20220402_1237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Klass',
        ),
    ]
