# Generated by Django 3.2.13 on 2022-04-12 10:34

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('car_name', models.CharField(default='', max_length=100)),
                ('driver_avatar', models.ImageField(default='threads/default.png', upload_to='')),
                ('car_number', models.CharField(default='', max_length=20)),
                ('car_color', models.CharField(default='', max_length=100)),
                ('phone', models.IntegerField(default='')),
                ('car_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='drive.car_type')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=False)),
                ('message', models.CharField(max_length=255, null=True)),
                ('driver', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='drive.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_longitude', models.FloatField(default=0)),
                ('from_latitude', models.FloatField(default=0)),
                ('to_longitude', models.FloatField(default=0)),
                ('to_latitude', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField()),
                ('car_type', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='drive.car_type')),
                ('driver', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='drive.driver')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('driver', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='drive.driver')),
            ],
            options={
                'verbose_name_plural': 'Location',
            },
        ),
    ]
