# Generated by Django 3.2.13 on 2022-04-12 11:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_alter_driver_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
