# Generated by Django 3.2.13 on 2022-04-14 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_tellme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tellme',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='tellme',
            name='name',
        ),
    ]
