# Generated by Django 3.2.13 on 2022-04-14 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0006_auto_20220414_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='TellMeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='tellme',
            name='tell_me_typ',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='drive.tellmetype'),
        ),
    ]
