# Generated by Django 3.2.13 on 2022-04-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0010_alter_tellme_tell_me_typ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tellmetype',
            name='image',
        ),
        migrations.AddField(
            model_name='tellmetype',
            name='text',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tellmetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
