# Generated by Django 3.2.13 on 2022-04-14 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0012_alter_tellmetype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tellme',
            name='tell_me_typ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drive.tellmetype'),
        ),
    ]
