# Generated by Django 3.2.13 on 2022-04-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0013_alter_tellme_tell_me_typ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tellme',
            name='tell_me_typ',
        ),
    ]
