# Generated by Django 3.2.13 on 2022-04-14 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0016_auto_20220414_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='tellme',
            name='select',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tellme',
            name='accident',
            field=models.CharField(blank=True, default='', max_length=110),
        ),
        migrations.AlterField(
            model_name='tellme',
            name='data_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tellme',
            name='massage',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tellme',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='tellme',
            name='place',
            field=models.CharField(blank=True, default='', max_length=110),
        ),
        migrations.AlterField(
            model_name='tellme',
            name='tell_me_typ',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='drive.tellmetype'),
        ),
    ]
