# Generated by Django 3.2.13 on 2022-04-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0017_auto_20220414_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tellme',
            name='select',
        ),
    ]
