# Generated by Django 3.2.13 on 2022-04-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0018_remove_tellme_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='tellme',
            name='select',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
