# Generated by Django 3.2.13 on 2022-04-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0019_tellme_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tellme',
            name='select',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
