# Generated by Django 3.2.13 on 2022-04-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0021_alter_tellme_tell_me_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tellme',
            name='massage',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
